### ISSUE TITLE
Requesting timeline on an un-implemented feature 

### ISSUE THREAD

**Issue by iamsyed0866** [itszechs/ZPlex#3]
After clicking on Watch Now. It's nothing happening and the movies doesn't play. In Zplex app @itszechs

**Comment by itszechs** [comment]
As mentioned on the repository description, this is a **Work-in-progress** Project.

Furthermore, this app is a BYOM (Bring your own media) type. It doesn't not come with any media, it's just a media manager similar to Plex the major difference being it will use cloud storage as source of media.

Lastly, this is a hobby project so there is no timeline on when it will be finished.
